jid: github@localhost/agent
password: testing
debug: true
jabber_debug: true
log_path: :error
pid_path: tmp/github.pid
herault_jid: herault@localhost/herault
actor_path: lib
actors:
  vertebra_github/actors/server:
  - "0.0.0.0"
  - 9292
  - "test"
  - "pass"
